# FOSSA configuration for cloudflare-launchpad (pure Apache-2.0)
version: 3

project:
  name: "cloudflare-launchpad"

options:
  allow-unresolved: true

# Stricter policies for pure Apache-2.0 foundation
policies:
  # Only allow the most permissive licenses
  allow:
    - "MIT"
    - "Apache-2.0"
    - "ISC"
    - "BSD-2-Clause"
    - "BSD-3-Clause"
    - "0BSD"
    - "Unlicense"
    - "CC0-1.0"

  # Flag anything questionable for review
  flag:
    - "LGPL-2.1"
    - "LGPL-3.0"
    - "MPL-2.0"

  # Deny anything that could complicate commercial use
  deny:
    - "GPL-2.0"
    - "GPL-3.0"
    - "AGPL-3.0"
    - "SSPL-1.0"
    - "BSL-1.1"  # No BSL in the foundation
    - "Copyleft"
    - "Proprietary"

notifications:
  email:
    - "josh@comfus.io"

vulnerability:
  enabled: true
  fail-on: "critical"