// Generated by Wrangler by running `wrangler types` (hash: e801fe501e0c3407efb79d37d00a8ab3)
// Runtime types removed manually in favor of continued use of @cloudflare/workers-types
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/app");
	}
	interface Env {
		ENVIRONMENT: string;
		ASSETS: Fetcher;
		AUTH_DB_URL: string;
		AUTH_DB_TOKEN: string;
		JWT_ACCESS_SECRET: string;
		JWT_REFRESH_SECRET: string;
		CACHE_URL?: string;
		CACHE_TOKEN?: string;
		AGENT_PROVISIONING_SECRET?: string;
	}
}
interface Env extends Cloudflare.Env {}
