/**
 * @file env.ts
 * Environment type definitions matching Cloudflare Worker configuration.
 *
 * @license LGPL-3.0-or-later
 */

/**
 * Environment bindings interface matching Cloudflare Worker configuration.
 * @see worker-configuration.d.ts generated by `wrangler types`
 */
export interface Env {
	AUTH_DB_URL: string;
	AUTH_DB_TOKEN: string;
	JWT_ACCESS_SECRET: string;
	JWT_REFRESH_SECRET: string;
}
