name: CI

on: push

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        bun-version: [ lts/*, latest ]
#        os: [ ubuntu-latest, windows-latest, macos-latest ]
#    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Setup Bun ${{ matrix.bun-version }}
#      - name: Setup Bun
#        uses: oven-sh/setup-bun@v2
#        with:
#          registry-url: "https://npm.jsr.io"
#          bun-version: canary

      - name: Setup Node
        uses: actions/setup-node@v4

#      - name: Install dependencies
#        run: |
#          bun install
#          bun pm untrusted

      - name: Install dependencies (Node)
        run: |
          npm install --legacy-peer-deps

#      - name: Run tests
#        run: |
#          bun install
#          bun test

      - name: Run tests (Node)
        run: npm run test